Further corrected documents placed within 120 chars, Ref 73.
OpenMS/OpenMS-docs pull request #110
Opened 2022-06-22 17:16 UTC by Jigidy

## Describe the change

Further documents from the "docs" folder have been updated to lay out within 120 character spaces, all documents from additional resources and faqs are now corrected. 
![Screenshot 2022-06-22 at 1 15 12 PM](https://user-images.githubusercontent.com/100532168/175098174-90d3a52c-e1e8-4a8a-a644-79c759ca8042.png)

![Screenshot 2022-06-22 at 1 15 36 PM](https://user-images.githubusercontent.com/100532168/175098204-40003065-7156-4c98-ad3a-dc2d25659657.png)

## PR checklist

- [X] I have added description of the change I'm proposing in the OpenMS Documentation.
- [X] I have read and followed [OpenMS Documentation Contributing guidelines](CONTRIBUTING.md).
- [X] I have attached a screenshot of the relevant area after this change.
- [X] `CHANGELOG.md` is updated.
- [X] I have added my name in [CONTRIBUTING.md](CONTRIBUTING.md#openms-documentation-contributors).

2022-06-23 04:48 UTC, tapaswenipathak requested changes
minor nits, let's make sure alignment in bullet points (lists) are proper, ex:
```
- this is a list sentence
continuing on another line.
```
```
- this is a list sentence
  continuing on another line.
```

i could have resolved the merge conflict for you, but i can't, please resolve any.

<img width="1314" alt="Screenshot 2022-06-23 at 10 12 15 AM" src="https://user-images.githubusercontent.com/4143778/175211617-db282e10-c6e4-4da4-94bc-8a0ffd11bf99.png">

2022-06-23 04:48 UTC, tapaswenipathak commented on docs/additional-resources/developer-guidelines-for-addding-new-dependent-libraries.md
> +  will link to as well - combining static and dynamic links will lead to linker errors or segfaults).
```suggestion
    will link to as well - combining static and dynamic links will lead to linker errors or segfaults).
```

2022-06-23 04:48 UTC, tapaswenipathak commented on docs/additional-resources/developer-guidelines-for-addding-new-dependent-libraries.md
> +dependencies of OpenMS are available as Debian package as well, the new library must be available (or made available) as
```suggestion
    dependencies of OpenMS are available as Debian package as well, the new library must be available (or made available) as 
```

2022-06-23 04:48 UTC, tapaswenipathak commented on docs/additional-resources/external-code-using-openms.md
> +package
```suggestion
    package
```

2022-06-23 04:48 UTC, tapaswenipathak commented on docs/additional-resources/openms-git-workflow.md
> +affecting the original project.
```suggestion
   affecting the original project.
```

2022-06-23 04:48 UTC, tapaswenipathak commented on docs/additional-resources/write-and-label-github-issues.md
> +   function.
```suggestion
       function.
```

2022-06-23 04:48 UTC, tapaswenipathak commented on docs/faqs/contributor-faq.md
> +or [contact us](../contact-us.md).
```suggestion
  or [contact us](../contact-us.md).
```

2022-06-23 04:48 UTC, tapaswenipathak commented on docs/faqs/contributor-faq.md
> +at `src/tests/class_tests/openms/executables.cmake`.
```suggestion
  at `src/tests/class_tests/openms/executables.cmake`.
```

2022-06-23 04:48 UTC, tapaswenipathak commented on docs/faqs/contributor-faq.md
> +develop branch in your fork of OpenMS.
```suggestion
   develop branch in your fork of OpenMS.
```

2022-06-24 16:08 UTC, Jigidy commented
All lines now aligned properly.

2022-06-24 16:16 UTC, tapaswenipathak approved these changes

2022-06-24 16:17 UTC, merged