Piwik scripts added
OpenMS/OpenMS-docs pull request #181
Opened 2022-12-13 11:27 UTC by rahul799

2022-12-20 20:35 UTC, tjeerdijk commented
Can you add the origin (link to piwik web site) of the script as a comment?

2022-12-21 19:43 UTC, rahul799 commented
Hey @tjeerdijk 
You can find the script here https://openms-web.piwik.pro/administration/apps/0f3e8416-7bda-4028-9f2e-3f1057cdb2f7/installation/sites

2023-02-16 10:58 UTC, jpfeuffer requested changes

2023-02-16 10:58 UTC, jpfeuffer commented on docs/conf.py
> +    app.add_js_file('../_static/js/piwik.js')
This is not how you add js files in sphinx:
https://docs.readthedocs.io/en/stable/guides/adding-custom-css.html

2023-03-28 09:00 UTC, jpfeuffer approved these changes

2023-03-28 09:03 UTC, merged